### ISSUE TITLE
Fix Accessibility across the site

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#103]
Step 1: @megansizemore Fill in the list below based on a standard that is industry-accepted
- Make sure images have `alt` tags
- Add lang attributes to <html> elements
- Make sure links have discernible text in footer, header, home page, learn/youth, /fellowship, /workspace , /about ( reference: https://dequeuniversity.com/rules/axe/4.6/link-name?application=AxeChrome )
- All page content should be contained by landmarks ( reference: https://dequeuniversity.com/rules/axe/4.6/region?application=AxeChrome )
- Color contrast throughout( blockquote on learn page, 'email careers@awesomeinc.org' on careers page,  HorizontalCard/FeaturedCard components fields used on home and events page, careers section of home page node.designedFor, inside iframe row on weekofcode page)
- Content should be contained by landmarks on footer, header, banner, /weekofcode, /contact, /events, /internships, /careers, /workspace, /learn, and home page ( reference: https://dequeuniversity.com/rules/axe/4.6/region?application=AxeChrome )
- ID attribute values must be unique on /learn, /learn/youth, /fellowship, /contact, and header ( reference: https://dequeuniversity.com/rules/axe/4.6/duplicate-id?application=AxeChrome )
- `<li>` elements must be contained in `<ul>` or `<ol>` on /intro-to-web-development, /learn/youth, and /parking pages
- Fix heading levels to only increase by one? ( reference: https://dequeuniversity.com/rules/axe/4.6/heading-order?application=AxeChrome )
- Document should have one main landmark for /internships, /events, /careers, /workspace pages ( reference: https://dequeuniversity.com/rules/axe/4.6/landmark-one-main?application=AxeChrome )
- Buttons on Careers page need to be wrapped in `<a>` instead of nested in the element. ( reference: https://dequeuniversity.com/rules/axe/4.6/nested-interactive?application=AxeChrome )
- Frames must have accessible name on /weekofcode and /contact pages ( reference: https://dequeuniversity.com/rules/axe/4.6/frame-title?application=AxeChrome )
- Form elements must have labels on Contact page ( reference: https://dequeuniversity.com/rules/axe/4.6/frame-title?application=axeAPI )

Step 2: Implement the list above

**Comment by megansizemore** [comment]
am going through the frontend and testing the accessibility with Lighthouse and [axe DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd/related). 
Commenting to document the process.

**Comment by megansizemore** [comment]
@raney24 @WillGarman I've updated the list with issues I found with the DevTools extension, let me know what you think.

**Comment by megansizemore** [comment]
Leaving out fixes for the header/navbar for now. 
Using the SEO component when it's ready should fix language attributes on all pages in the future.
For now I am going through and adding aria-labels, descriptive text, `alt` tags, `ol` or `ul` tags for lists, change heading  styling for sizing, and fixing color contrast where needed.
