### ISSUE TITLE
Create 5 Across Page

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#13]

**Comment by raney24** [comment]
Create 5 Across page to be similar to awesomeinc.org/events/5across

Data sources
- Events - query upcoming 5A event
- [NEW] 5A winners - use this for recent winner banner section and past winners section

Hold off on the Sponsors section for now

**Comment by raney24** [comment]
To make sure an `event` can be filtered, we can use `references` from Sanity.

https://www.sanity.io/docs/reference-type

**Comment by WillGarman** [comment]
Pull request: #20
