### ISSUE TITLE
Fix CourseTable responsiveness

### ISSUE THREAD

**Issue by megansizemore** [ainc/ainc-gatsby-sanity#137]
The CourseTable component on the learn/adults page may need to be more responsive? Right now there's horizontal scroll to see the entire table. I think it could be better for mobile to display the table vertically, but let me know what you all think. 
@raney24 @WillGarman 
<img width="438" alt="Screen Shot 2023-05-24 at 1 57 39 PM" src="https://github.com/ainc/ainc-gatsby-sanity/assets/97846828/22a6be9f-4778-4bdd-a0f7-d4a8d13bfc36">

**Comment by WillGarman** [comment]
For sure good point, we actually have a project open right now for the design team to come up with a new way to display the courses for that exact reason
