### ISSUE TITLE
Running svg on windows throws error

### ISSUE THREAD

**Issue by tranthle** [ainc/ainc-gatsby-sanity#138]
When trying to load a page with an svg, it throws this error: 
`react dom string contains an invalid character`

Note: the solution might be related [to this](https://stackoverflow.com/questions/63517356/receiving-invalidcharactererror-string-contains-an-invalid-character-from-imp)

**Comment by raney24** [comment]
@tranthle Can you confirm that the homepage works for you on the main branch? I replaced the SVG's with icons
