### ISSUE TITLE
Create Bootcamp Page

### ISSUE THREAD

**Issue by colinsmith3** [ainc/ainc-gatsby-sanity#14]
Sanity Document Types:
- Companies
- Testimonials
- Stats
- Meet Stephen

**Comment by raney24** [comment]
This is mostly complete. Need to fix the testimonials from bootcampers. Text seems to be stretching in one line. Also need to add action to the Apply Now buttons

**Comment by raney24** [comment]
Responsiveness is also a major piece of this
