### ISSUE TITLE
Fix outdated Query issues on local server launch

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#159]
@ethangambles Can you add the error in here...

**Comment by ethangambles** [comment]
`Deprecated syntax of sort and/or aggregation field arguments were found in your     
query (see https://gatsby.dev/graphql-nested-sort-and-aggregate). Query was automatically converted to a new syntax. You should update query in your code.

Current query:

query fiveAcrossQuery($currentDate: Date!) {
  allSanityEvents(
    filter: {reference: {eventTypeName: {eq: "5 Across"}}, date: {gte: $currentDate}}    
    sort: {order: ASC, fields: date}
    limit: 1
  ) {
    nodes {
      eventName
      date(formatString: "MMMM D, YYYY")
      host
      location
      linkToEvent
      picture {
        asset {
          gatsbyImageData
        }
      }
      reference {
        eventTypeName
      }
    }
  }
  allSanityFiveAcrossWinners(sort: {order: ASC, fields: WinningDate}) {
    edges {
      node {
        WinningDate
        companyTitle
        FounderNames
        founderVideo
        image {
          asset {
            gatsbyImageData(aspectRatio: 1, height: 300)
          }
        }
      }
    }
  }
  allSanityFiveAcrossSponsors {
    nodes {
      presetingSponsorName
      presentingSponsorLink
      presentingSponsorImage {
        asset {
          gatsbyImageData
        }
      }
      titleSponsorName
      titleSponsorLink
      titleSponsorImage {
        asset {
          gatsbyImageData
        }
      }
      suppourtingSponsors {
        image {
          asset {
            gatsbyImageData(layout: CONSTRAINED)
          }
        }
        link
        alt
      }
    }
  }
}

Converted query:

query fiveAcrossQuery($currentDate: Date!) {
  allSanityEvents(
    filter: {reference: {eventTypeName: {eq: "5 Across"}}, date: {gte: $currentDate}}    
    sort: {date: ASC}
    limit: 1
  ) {
    nodes {
      eventName
      date(formatString: "MMMM D, YYYY")
      host
      location
      linkToEvent
      picture {
        asset {
          gatsbyImageData
        }
      }
      reference {
        eventTypeName
      }
    }
  }
  allSanityFiveAcrossWinners(sort: {WinningDate: ASC}) {
    edges {
      node {
        WinningDate
        companyTitle
        FounderNames
        founderVideo
        image {
          asset {
            gatsbyImageData(aspectRatio: 1, height: 300)
          }
        }
      }
    }
  }
  allSanityFiveAcrossSponsors {
    nodes {
      presetingSponsorName
      presentingSponsorLink
      presentingSponsorImage {
        asset {
          gatsbyImageData
        }
      }
      titleSponsorName
      titleSponsorLink
      titleSponsorImage {
        asset {
          gatsbyImageData
        }
      }
      suppourtingSponsors {
        image {
          asset {
            gatsbyImageData(layout: CONSTRAINED)
          }
        }
        link
        alt
      }
    }
  }
}
`

I see this on `pages/index`, `pages/alumni/index`, and `pages/into-to-web-development/index`.
