### ISSUE TITLE
Fix course cards on homepage to display same size image

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#162]

**Comment by ethangambles** [comment]
I tried to change the query to allow for bigger images, and did the same with the <GatsbyImage /> component, and the images stayed relatively the same size. Seems to me the new images are smaller than the Coding Club one.

**Comment by raney24** [comment]
@ethangambles I think I fixed this and should be on `main` now. Can you test and make sure this works for you?

**Comment by ethangambles** [comment]
@raney24 That looks fixed, although the images are a bit blurry for me. Not sure if that's local or something we can fix.

**Comment by raney24** [comment]
@ethangambles Yeah, that's because of the image size. We'll need to upload an image that's larger in size - that can be the responsibility of the "content team"
