### ISSUE TITLE
Fix 5across red banner across top of site

### ISSUE THREAD

**Issue by ethangambles** [ainc/ainc-gatsby-sanity#168]

**Comment by raney24** [comment]
@ethangambles Can you elaborate more on this one? Is it where the banner shows up but with no text?

**Comment by ethangambles** [comment]
@raney24 Yes, sorry about that. The red banner across the top of the website has no 5across text. Currently, it should say "Sign up here for 5 Across - October 25, 2023" with a link to the eventbrite page: https://www.eventbrite.com/e/705466097087
