### ISSUE TITLE
Create Podcast page

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#2]
Create a page similar to the /blog page for our podcast. This can live at /podcast.

Refer to this [commit](https://github.com/ainc/ainc-gatsby-sanity/commit/145ae020ae2aed41faa6b50d5e16c1b098fd920e) for reference on how this is being imported. 

In short, we used [gatsby-source-rss-feed](https://www.gatsbyjs.com/plugins/gatsby-source-rss-feed/) to import the podcasts from Anchor (at this URL: https://anchor.fm/s/81dfae4/podcast/rss)

I don't know what data we get from Anchor, so it may not match the /blog exactly. 

Since it likely won't be the exact same, we can create a new component.

**Comment by WillGarman** [comment]
The podcast page has been created and is to be fully functional. 
Branch -> [https://github.com/ainc/ainc-gatsby-sanity/tree/podcast](https://github.com/ainc/ainc-gatsby-sanity/tree/podcast)

There is a GraphQL error that has popped up and am not sure where it came from, I'm thinking it is something that happened outside of my control/some other change. I think it is worth a shot to try and boot it up not on my side.

![image](https://user-images.githubusercontent.com/73144742/185042696-39595685-04fd-44e2-a604-2b860a54ec32.png)
