### ISSUE TITLE
Button Modal Component

### ISSUE THREAD

**Issue by colinsmith3** [ainc/ainc-gatsby-sanity#21]
Use react bootstrap modal. 
Must be reusable.

**Comment by raney24** [comment]
@colinsmith3 how is this coming? Have you made any progress?

**Comment by colinsmith3** [comment]
> @colinsmith3 how is this coming? Have you made any progress?

I've barely been able to look into it. I've been working on the UBS page with Garrett and still confused about my testimonial component for the bootcamp page. I'll try to dive into it this weekend if I have time.

**Comment by raney24** [comment]
@WillGarman Are you able to take this on next? Comment here or Slack with questions if you have any.

**Comment by WillGarman** [comment]
Yep I will check it out!
