### ISSUE TITLE
Languages used on bootcamp page

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#227]

**Comment by raney24** [comment]
These should probably be in one or two columns instead of all in one row. 

![image](https://github.com/ainc/ainc-gatsby-sanity/assets/4423998/fbda4766-cefc-48bd-998a-fbe17ad52abe)

**Comment by ethangambles** [comment]
@raney24 is that on mobile? It looks good to me on laptop

**Comment by ethangambles** [comment]
@raney24 I made it look a lot better on mobile, but I also had to change how they look on large screens. I just made them 2 rows instead of 1. Let me know what you think, we can easily change it back if necessary.

**Comment by raney24** [comment]
@ethangambles I like it, we'll re-open if someone else has different thoughts.
