### ISSUE TITLE
Bootcamp page changes

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#229]

**Comment by raney24** [comment]
Stephen's comments: 

- [ ] Shields under the "answer honestly" section have text overflowing/spaced oddly
- [ ] Hear from our alumni section:
-  [ ] start with Melo's story since she's at the top
have stories switch from hovering (instead of requiring a click on the picture)
- [ ] maybe some sort of visual indicator of whose story is selected (outlining the picture of the current story, or something like that)
-  [ ]Pics look low-res

- [ ] second sentence on the left says "that's why we want to help 120 everyone we can..." we need to take that 120 out of there
https://ainc.slack.com/files/US0L449LM/F06BLNMFQKT/screen_shot_2023-12-21_at_1.38.41_pm.png

- [ ]Under the Job Guarantee section,
in the red area, starting salary should go up to $59k and say 2023 average under it
Graduation Rate should say 2016-2023 instead of through 2020

- [ ]Under Hiring Partners, if we could get a line that just says "and over 50 more" under the logos. Right now it seems like we've only hired out to 10 companies

- [ ]Under the cost, the up front payment needs to be updated to $15,500

- [ ] Also under the cost the ISA threshold is up to $45k from 40k (last line of that paragraph)

**Comment by raney24** [comment]
@ethangambles Making some of these changes here: https://github.com/ainc/ainc-gatsby-sanity/tree/229-bootcamp-page-changes

**Comment by ethangambles** [comment]
@raney24 I think everything is completed except for the pics looking low-res. They look the same to me on the old site, so I think that may just be the best images we have.

**Comment by raney24** [comment]
@ethangambles thanks! I'll ask Stephen what he meant by that
