### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#235]

**Comment by raney24** [comment]
Need to add our tutorials from the old site. 

https://github.com/ainc/ainc-2018/tree/master/_tutorials

Probably best to create a document for this as well, can be similar to the blog doc.

**Comment by raney24** [comment]
@ethangambles I meant to talk about this at our meeting, can you take this issue?

**Comment by ethangambles** [comment]
@raney24 I can, but I'm a little confused as to what the end goal should be. Are all of these separate pages, sanity documents, etc.?

**Comment by raney24** [comment]
Yes, separate pages for each. Might be nice to have a landing page with a simple list like the [press page](https://awesomeinc.org/press/). This is an example of what we had before: 

https://old.awesomeinc.org/tutorials/construct-block-game/

**Comment by ethangambles** [comment]
@raney24 added at https://awesomeinc.org/tutorials/
