### ISSUE TITLE
Make new sitemap

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#246]
![image](https://github.com/ainc/ainc-gatsby-sanity/assets/4423998/a753c790-d82d-432a-aa64-c40d5988fb72)

@ColinCarver10 Can you help with this? 

Looks like this didn't make it over with the site migration. This will help with our SEO. 

https://support.google.com/webmasters/answer/7451001#error_list&zippy=%2Csubmit-a-sitemap

**Comment by ColinCarver10** [comment]
@raney24 Can this be closed?
