### ISSUE TITLE
Google Search Index crawler

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#282]
Hey @ethangambles @ColinCarver10 Can either of you tackle this? Shouldn't take more than 1 hour, but there are some pages that need to be indexed are being avoided. I suspect because our robots.txt has something telling Google not to. 

Do you have to the console? Here is an emaple:

![image](https://github.com/ainc/ainc-gatsby-sanity/assets/4423998/612b4ee8-dafa-4893-9c55-96207b1bbc90)

I think there is a way to export into a csv and you possibly sort or filter out all values that DON'T have a subdomain. This is the filter for does NOT need to be indexed:

- anything with a subdomain 
- components that are on our domain (the shields row component in screenshot is an example)

**Comment by ethangambles** [comment]
Adding this to my list.

**Comment by raney24** [comment]
https://breaktheweb.agency/seo/why-pages-arent-indexed/#:~:text=Some%20of%20the%20most%20common,know%20that%20the%20page%20exists.
