### ISSUE TITLE
Continuous Deployment / Staging branches with Sanity Studio

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#29]
Each time someone makes a change to Sanity, it often breaks the production dataset. We need to set up a way for a staging dataset and a production dataset. 

Link for ref: https://www.sanity.io/guides/multi-environment-deployments

**Comment by WillGarman** [comment]
Would our "dataset" be considered the GraphQL from Sanity to Gatsby?

**Comment by raney24** [comment]
@WillGarman Let's just set up a manual process that is well-documented on how to import/export the `dev` dataset to the `production` dataset. 

Potential gotcha's: 
- How does content merge? For example, does content created during the dev process get overwritten during the import

TODO: Figure out tags when running `import/export` dataset commands

**Comment by WillGarman** [comment]
Notes: 

- ### Workflow to create new schema's and documents for production
  - Use `local` machine to create schema on your personal tagged dataset [()](https://github.com/ainc/ainc-gatsby-sanity/commit/83a6e89290f1b83a4fd9d0a0223cc858c05bca8b#:~:text=%3A%20%27beta%27-,graphqlTag,-%3A%20%27beta%27)
  - Export from your tagged dataset, then import into `dev` dataset using either `--missing` or `--replace` flags [(Documentation)](https://www.sanity.io/docs/importing-data#:~:text=tar.gz%20production-,Protip,-The%20import%20will)
  - In the `dev` dataset, then add documents to your new schema in the Sanity Dashboard
  -  Then export from `dev` dataset, and import into `production` dataset using the `--missing` flag (Will test the `--replace` flag)
  - Possible have to do `sanity graphql deploy` to update the GraphQL
  - Yay you're done... hopefully (This is the rough process going into testing)

**Comment by raney24** [comment]
@WillGarman Anything left to keep this issue open? Is the above documentation in the Readme?

**Comment by WillGarman** [comment]
> @WillGarman Anything left to keep this issue open? Is the above documentation in the Readme?

@raney24 the documentation has not been added to the readme. Once it gets put in there then this issue doesn't need to be open any longer

**Comment by raney24** [comment]
@WillGarman Can you add that in and then close this?

**Comment by WillGarman** [comment]
Added!
