### ISSUE TITLE
All Mobile Bug Fixes

### ISSUE THREAD

**Issue by ColinCarver10** [ainc/ainc-gatsby-sanity#318]
Bootcamp Page:
- [x] "What we accomplished in 2023" buttons overlap.
- [x] "Our core values" text hard to read, images are super small.
- [x] Upcoming events not all same size. 5 Across Event text outside of viewable area.

Footer:
- [x] Newsletter sign up button margin too small on bottom.
- [x] Do we want social media links spanning vertically?

/Learn/Youth Page:
- [x] C.O.D.E title overflow
- [x] Random period under book a call button.
- [x] Lots of inconsistent margin / padding.

/Learn/Adult Page:
- [x] Horizontal page overflow
- [x] Computer Image overflow
- [x] No margin between cards.
- [x] Horizontal scroll on learn cards (Fixed in PR #281)

/idea:
- [ ] Scroll inside of form is confusing. Can't tell if you are scrolling the page or the form.

/fellowship:
- [x] No margin on Title
- [ ] Header Image not centered
- [ ] Inconsistent padding all around.
- [x] Sponsors text a bit too large, makes it look uneven.

/events/5across:
- [x] Join us on next 5 across section has no padding on the bottom
- [x] Too much white space above "Our most recent winner"

/events:
- [ ] Lots of padding at bottom of event card.

/about:
- [x] What we accomplished buttons overlapping.
- [x] Lots of top padding in the "Learn more about what we do" cards
- [x] Meet the team section has a lot of x-padding, could potentially make this section shorter by removing it?

/what-we-do:
- [x] Too much bottom padding in header
- [x] Too much padding in Our Programs (top & bottom)

/Blog:
- [x] Search feature, horizontal scroll & padding not good.
- [x] Read more overflow
- [x] No pagination

/Careers:
- [x] Email text size at bottom is a bit small.

Internships:
- [ ] Teams modal overflow
- [x] FAQ modal overflow
- [x] Some excess padding/margin?

**Comment by ethangambles** [comment]
- [ ] blog
- [ ] internship modal scroll to top on close
- [ ] youth 'engage with students'
