### ISSUE TITLE
Margin on ModalCustom 

### ISSUE THREAD

**Issue by megansizemore** [ainc/ainc-gatsby-sanity#40]
The modal has random margin that adds unnecessary scroll when the modal is opened.

**Comment by raney24** [comment]
@WillGarman Can you take a look at this? For whatever reason, the body behind the modal has a scroll when the modal is opened. 

According to [Bootstrap Docs](https://getbootstrap.com/docs/5.0/components/modal/#:~:text=Modals%20are%20built%20with%20HTML%2C%20CSS%2C%20and%20JavaScript.%20They%E2%80%99re%20positioned%20over%20everything%20else%20in%20the%20document%20and%20remove%20scroll%20from%20the%20%3Cbody%3E%20so%20that%20modal%20content%20scrolls%20instead.) it is not supposed to do that. `body` is getting `overflow: hidden` applied like it is supposed to when a modal is opened, but there is still scrolling that happens.

**Comment by WillGarman** [comment]
Yep I will take a look
