### ISSUE TITLE
Create 5Across Program guide

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#48]
1. Create the page for mobile devices
2. Create and connect the sanity documents

**Comment by WillGarman** [comment]
Reference: https://www.awesomeinc.org/5aprogram

Could have a Sanity doc for "Judges" 
- Picture
- Name
- Job/Company

Sanity Doc for "Presenters"
- Picture/Logo
- Company Name

Possibly use the current Sanity Doc for 5A Sponsors

**Comment by raney24** [comment]
#58
