### ISSUE TITLE
Core Values Section

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#5]
Core Values section images aren't being displayed. Could be because of a `z-index` problem with the bg and filter, or something else entirely. 

[This  commit](https://github.com/ainc/ainc-gatsby-sanity/commit/8661cb0e5d070b9708875ed672a6a04b72234dcd) has the most relevant code.

**Comment by WillGarman** [comment]
Here is an update for this issue: PR #24
