### ISSUE TITLE
Notes Pages & Sanity Doc

### ISSUE THREAD

**Issue by WillGarman** [ainc/ainc-gatsby-sanity#51]
Sanity Doc could include
- Note Title (Auto generate link from title slug)
- [Portable Text Editor](https://www.sanity.io/docs/portable-text-editor-configuration) (To  allow manual writing or iframe embed)

Then need to make these pages:

[/mobile-apps-with-flutter](https://www.awesomeinc.org/mobile-apps-with-flutter)
[/intro-to-design](https://www.awesomeinc.org/intro-to-design)
[/android-crash](https://www.awesomeinc.org/android-crash)
[/android-sportsball-fanatic](https://www.awesomeinc.org/android-sportsball-fanatic)
[/basicweb-crash](https://www.awesomeinc.org/basicweb-crash)
[/after-school-coding-club](https://www.awesomeinc.org/after-school-coding-club)
[/dayofcode](https://www.awesomeinc.org/dayofcode)
[/frontweb2](https://www.awesomeinc.org/frontweb2)
[/ios-crash](https://www.awesomeinc.org/ios-crash)
[/k12-teacher](https://www.awesomeinc.org/k12-teacher)
[/php-crash](https://www.awesomeinc.org/php-crash)
[/unity-crash](https://www.awesomeinc.org/unity-crash)
[/weekofcode-hw](https://www.awesomeinc.org/weekofcode-hw)
[/woc](https://www.awesomeinc.org/woc)

**Comment by raney24** [comment]
Steps:
1. Create sanity document
2. [Implement picture uploading](https://medium.com/@kimbjrkman/how-to-use-inline-images-in-rich-text-with-sanity-io-c42594baa509)
3. Create frontend component
4. Create documents

Fields for Sanity doc
- Notes age range, ie adults, youth, other
- Title
- Author (optional)
- Body

**Comment by raney24** [comment]
Current site Gdoc embed: https://github.com/ainc/ainc-2018/blob/master/_layouts/notes-gdoc.html
