### ISSUE TITLE
Create dynamic page titles

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#63]
Page titles should be included in each page. It would be nice to have these be dynamic using the `Layout.js` component. Do you think that is the best way to do that? This will allow us to code the page titles, or we can pass page title from a sanity document, etc.

**Comment by WillGarman** [comment]
So we have 2 options, we can pass the SEO details to `<Layout/>`. Or we can use the `<SEO/>` module that is already made.

**Either way we can pass data from queries**. I like the idea of having an SEO component on each page, it will be very easy to find and change SEO info. 

Example: 
```
return (
    <Layout>
      <SEO title={querydatahere} description="" keywords="" />
      ...

 ```
 @raney24

**Comment by raney24** [comment]
@WillGarman Let's use the `<SEO>` module, that makes more sense to me

**Comment by WillGarman** [comment]
@raney24 I think we should come up with a system of giving page SEO details soon. Such as a Sanity doc or if we just want to hard code them in for now and go back later.

But just so we can start having it uniform for new pages built 

(_or just not worry about it for now and go back later and change all the pages_)

**Comment by WillGarman** [comment]
@raney24 Do you think it a better idea to come up with an SEO solution (Sanity Doc?) now for the future pages to be built on, or we could just do an overhaul and change all of the pages at the end however we want to do it

**Comment by raney24** [comment]
@WillGarman I like having a system right now. My thought is this flow:

1. Check if page title is defined by sanity (not sure how we want to do this? This is maybe phase 2
2. Use a variable defined in component 
3. Then implement like so: 

```
// layout.js
<title>{ page.title } | Awesome Inc </title>

// {page_name}.js
const SamplePage = () => {

  pageTitle = "Sample Page"  

  return (
    ...
  )
}
```

**Comment by WillGarman** [comment]
Looks good to me, do we want to just use the title in in the `Layout` tag instead of doing the `SEO` tag.

Also do we want to auto add `| Awesome Inc` to the end of every page. Just not sure if this will affect SEO.

**Comment by raney24** [comment]
@WillGarman actually, it probably makes more sense to just use the `<SEO>` tag for `title, description, and keywords`. The same way I was describing above, but just inside `<SEO>` instead of `<Layout>`. To me, that makes more sense, Layout is more like design/looks. I could be convinced otherwise. 

And yes, I think when we implement `<SEO>`, it should add ` | Awesome Inc` to the end.
