### ISSUE TITLE
Create /Parking Page

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#66]
@megansizemore I can't remember if you had created this or not? If not, can I put this on your list? 

awesomeinc.org/parking

**Comment by WillGarman** [comment]
@raney24 just a heads up I also have that page here #50

**Comment by megansizemore** [comment]
@raney24 It's on my list, thanks!

**Comment by raney24** [comment]
@WillGarman Oops, I'm deleting this one.
