### ISSUE TITLE
(Investigate) Fix x-scroll on various pages

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#77]
Press page
Homepage (podcase section)
About page
Workspace
...and maybe more

On the homepage, this was fixed by making sure all Sections with `row` were placed inside of a `container`

**Comment by raney24** [comment]
@megansizemore @WillGarman I added an attempt to fix this by changing the structure of the footer with this commit... 
https://github.com/ainc/ainc-gatsby-sanity/commit/03db9286e1d4739d4255c55353957ac22ac17973

I'm not confident that will fix it but I also still can't replicate it which is really weird since I saw it happen on both of your devices.

**Comment by WillGarman** [comment]
@raney24 I noticed this only seems to be happening locally, seems fine on the live dev site. confirmed with @megansizemore
