### ISSUE TITLE
Podcast page isn't generating

### ISSUE THREAD

**Issue by raney24** [ainc/ainc-gatsby-sanity#9]
`.createPage` is not allowing the site to build on Netlify. 

error message: `error UNHANDLED REJECTION Couldn't find temp query result for "/podcast".`

[Build link](https://app.netlify.com/teams/ainc/builds/630822894970450008c5d21f)

Duplicate by uncommenting [this code](https://github.com/ainc/ainc-gatsby-sanity/blob/main/web/gatsby-node.js#L33) and running `netlify build` locally.

**Comment by raney24** [comment]
@WillGarman See above...
Netlify wasn't able to publish the build with podcast page, can you take a look at this? 

[This might be the solution](https://github.com/gatsbyjs/gatsby/issues/35018#issuecomment-1161732245)

**Comment by WillGarman** [comment]
Got it will look now

**Comment by raney24** [comment]
I've made some progress but I'm still getting an error. It looks like the 

The error: `WebpackError: document is not defined` was being approached in the wrong way I think. According to Gatsby docs, it says: 

>To fix this, find the offending code and either

> check before calling the code if window is defined so the code doesn’t run while Gatsby is building (see code sample below) or
> if the code is in the render function of a React.js component, move that code into componentDidMount which ensures the code doesn’t run unless it’s in the browser.

The offending code is in `components/Podcast/Podcast.js` since that is where we create a document. So I changed that code here: #10 

Take a look at that and try to pull it and see if you get anywhere with the error I'm getting.

**Comment by WillGarman** [comment]
LOG:
---
```
gitpod /workspace/ainc-gatsby-sanity/web (podcast-hotfix) $ gatsby build
success compile gatsby files - 1.554s
success load gatsby config - 0.034s
success load plugins - 0.646s
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modyfing the document head. Learn more at https://gatsby.dev/gatsby-head
success onPreInit - 0.006s
success delete worker cache from previous builds - 0.004s
info [sanity] Fetching remote GraphQL schema
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
success initialize cache - 0.559s
success copy gatsby files - 0.181s
success Compiling Gatsby Functions - 0.233s
success onPreBootstrap - 0.246s
success createSchemaCustomization - 0.011s
info [sanity] 0 documents updated.
success Checking for changed pages - 0.001s
success source and transform nodes - 4.200s
info Writing GraphQL type definitions to /workspace/ainc-gatsby-sanity/web/.cache/schema.gql
success building schema - 1.346s
info [sanity] Fetching remote GraphQL schema
info [sanity] Fetching remote GraphQL schema
info [sanity] Fetching remote GraphQL schema
success createPages - 0.108s
info [sanity] Fetching remote GraphQL schema
info [sanity] Fetching remote GraphQL schema
info [sanity] Fetching remote GraphQL schema
info [sanity] Fetching remote GraphQL schema
success createPagesStatefully - 0.107s
info Total nodes: 718, SitePage nodes: 26 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success Cleaning up stale page-data - 0.002s
success onPreExtractQueries - 0.001s
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL
info [sanity] Transforming to Gatsby-compatible GraphQL SDL
info [sanity] Stitching GraphQL schemas from SDL

ERROR #85911  GRAPHQL

There was a problem parsing "undefined"; any GraphQL
fragments or queries in this file were not processed.

This may indicate a syntax error in the code, or it may be a file type
that Gatsby does not know how to parse.

File: src/components/Podcast/Podcast.js

failed extract queries from components - 3.211s
```
---

I think I am getting very close I am running into this error on running `gatsby build` , I feel like there may be something simple I either need to figure out. 

Here are some things I have referenced in relation to my error but they aren't much help [#36472](https://github.com/gatsbyjs/gatsby/issues/36472) [#34857](https://github.com/gatsbyjs/gatsby/issues/34857)

**Comment by WillGarman** [comment]
Also, I thought I was doing super well for the past coupe hours. But it turns out I just did a big loop all the way back to the same error 😞

**Comment by WillGarman** [comment]
#11
