### ISSUE TITLE
Create /team-alpha page

### ISSUE THREAD

**Issue by WillGarman** [ainc/ainc-gatsby-sanity#91]
https://www.awesomeinc.org/team-alpha

- Sanity Doc
   - Name
   - Picture
   - Team/Role
   - Favorite Rule
   - Favorite Song
   - Favorite Person
   - Random Fact

**Comment by megansizemore** [comment]
this still isn't perfect, but could technically work for now.
changes to make:

- buttons need to be same width/height
- overlay needs match the width/height of image
