### ISSUE TITLE
Create FAQ pages

### ISSUE THREAD

**Issue by WillGarman** [ainc/ainc-gatsby-sanity#92]
These pages are the same just with different questions

Could most likely create a sanity doc of some sort

- https://www.awesomeinc.org/learn/coding-club-faq
- https://www.awesomeinc.org/india/faq (Also here #74 )

**Comment by raney24** [comment]
1. Create an FAQ component
2. Pass in prop (object) that holds the questions and answers
- `{question: answer}`
3. FAQ component maps thru prop with Q&A
4. **Future**: For now, hardcode q&a, but we can eventually make this into a Sanity document
